// // This file is "main.dart"
// import 'dart:ui';

// import 'package:freezed_annotation/freezed_annotation.dart';
// import 'package:flutter/foundation.dart';

// // required: associates our `main.dart` with the code generated by Freezed
// part 'user_model.freezed.dart';
// // optional: Since our Person class is serializable, we must add this line.
// // But if Person was not serializable, we could skip it.
// part 'user_model.g.dart';

// @freezed
// class InvestmentStoreModel with _$InvestmentStoreModel {
//   // final String firstName;
//   const factory InvestmentStoreModel(
//       {required String type,
//       required String floor,
//       required String space,
//       required String price,
//       required ImageDescriptor img // or image ? or file ?
//       }) = _InvestmentStoreModel;

//   factory InvestmentStoreModel.fromJson(Map<String, Object?> json) =>
//       _$InvestmentStoreModelFromJson(json);
// }
